function b = b_cartpole(in1,in2)
%B_CARTPOLE
%    B = B_CARTPOLE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    15-Sep-2025 11:27:45

dth = in1(4,:);
g = in2(4,:);
k_tors = in2(9,:);
l = in2(3,:);
mP = in2(1,:);
th = in1(2,:);
t2 = sin(th);
b = [-dth.^2.*l.*mP.*t2;-k_tors.*th+g.*l.*mP.*t2];
end
