function out1 = jacobian_P(in1,in2)
%jacobian_P
%    OUT1 = jacobian_P(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Sep-2025 10:22:25

l = in2(3,:);
th = in1(2,:);
out1 = reshape([1.0,0.0,-l.*cos(th),-l.*sin(th)],[2,2]);
end
