function out1 = jacobian_C(in1,in2)
%jacobian_C
%    OUT1 = jacobian_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    13-Sep-2025 10:22:25

out1 = reshape([1.0,0.0,0.0,0.0],[2,2]);
end
