function b = b_cartpole(in1,in2)
%B_CARTPOLE
%    B = B_CARTPOLE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    12-Feb-2026 15:52:01

dth = in1(4,:);
g = in2(4,:);
l = in2(3,:);
mP = in2(1,:);
th = in1(2,:);
t2 = sin(th);
b = [-dth.^2.*l.*mP.*t2;g.*l.*mP.*t2];
end
