function out1 = jacobian_C(in1,in2)
%jacobian_C
%    OUT1 = jacobian_C(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    12-Feb-2026 15:52:01

out1 = reshape([1.0,0.0,0.0,0.0],[2,2]);
end
