function keypoints = keypoints_cartpole(in1,in2)
%KEYPOINTS_CARTPOLE
%    KEYPOINTS = KEYPOINTS_CARTPOLE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 25.2.
%    12-Feb-2026 15:52:01

l = in2(3,:);
th = in1(2,:);
x = in1(1,:);
keypoints = reshape([x,0.0,x-l.*sin(th),l.*cos(th)],[2,2]);
end
